# Generated by Django 4.2.2 on 2023-07-02 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=255)),
                ('enrollment_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('courses', models.ManyToManyField(related_name='subjects', to='courses.subject')),
                ('student_username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollment',
                'db_table': 'activity_enrollment',
                'ordering': ('-date_added',),
            },
        ),
    ]
